import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const candidates = [
  // Engineering
  {
    name: 'Priya Sharma',
    role: 'Senior Full-Stack Engineer',
    roleSlug: 'senior-full-stack-engineer',
    skills: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'AWS'],
    summary: '6 years building SaaS products. Led frontend at two funded startups. Obsessed with performance.',
    socialLinks: { linkedin: 'https://linkedin.com', github: 'https://github.com' },
    email: 'priya.sharma@example.com',
    phone: '+1-555-001-0001',
    currentBid: 2000,
    category: 'engineering',
    status: 'active',
    rank: 1,
    peakRank: 1,
    profileViews: 142,
    unlockCount: 8,
    bidCount: 1,
    daysListed: 12,
  },
  {
    name: 'Marcus Webb',
    role: 'Staff Software Engineer',
    roleSlug: 'staff-software-engineer',
    skills: ['Go', 'Kubernetes', 'gRPC', 'Kafka', 'Terraform'],
    summary: 'Distributed systems engineer. 8 years scaling infra at Series B through IPO companies.',
    socialLinks: { linkedin: 'https://linkedin.com', github: 'https://github.com' },
    email: 'marcus.webb@example.com',
    phone: null,
    currentBid: 1800,
    category: 'engineering',
    status: 'active',
    rank: 2,
    peakRank: 1,
    profileViews: 98,
    unlockCount: 5,
    bidCount: 1,
    daysListed: 7,
  },
  {
    name: 'Anya Kowalski',
    role: 'Frontend Engineer',
    roleSlug: 'frontend-engineer',
    skills: ['React', 'Next.js', 'Figma', 'CSS', 'Storybook'],
    summary: 'I bridge design and engineering. Built a design system used by 60+ engineers.',
    socialLinks: { portfolio: 'https://example.com', github: 'https://github.com' },
    email: 'anya.k@example.com',
    phone: '+1-555-001-0003',
    currentBid: 1500,
    category: 'engineering',
    status: 'active',
    rank: 3,
    peakRank: 3,
    profileViews: 67,
    unlockCount: 3,
    bidCount: 1,
    daysListed: 5,
  },
  {
    name: 'Darius Okafor',
    role: 'Backend Engineer',
    roleSlug: 'backend-engineer',
    skills: ['Python', 'Django', 'FastAPI', 'Redis', 'Postgres'],
    summary: 'API-first developer who ships clean, well-tested code. Open-source contributor.',
    socialLinks: { github: 'https://github.com' },
    email: 'darius.o@example.com',
    phone: null,
    currentBid: 1200,
    category: 'engineering',
    status: 'active',
    rank: 4,
    peakRank: 4,
    profileViews: 45,
    unlockCount: 2,
    bidCount: 1,
    daysListed: 3,
  },
  {
    name: 'Li Wei Chen',
    role: 'iOS Engineer',
    roleSlug: 'ios-engineer',
    skills: ['Swift', 'SwiftUI', 'Combine', 'Xcode', 'Core Data'],
    summary: 'Published 4 apps with 500k+ combined downloads. Love building delightful mobile experiences.',
    socialLinks: { x: 'https://x.com', portfolio: 'https://example.com' },
    email: 'li.chen@example.com',
    phone: '+1-555-001-0005',
    currentBid: 900,
    category: 'engineering',
    status: 'active',
    rank: 5,
    peakRank: 5,
    profileViews: 31,
    unlockCount: 1,
    bidCount: 1,
    daysListed: 2,
  },
  // Design
  {
    name: 'Sofia Martinez',
    role: 'Senior Product Designer',
    roleSlug: 'senior-product-designer',
    skills: ['Figma', 'User Research', 'Prototyping', 'Design Systems', 'Framer'],
    summary: 'I own design end-to-end: research, wireframes, final pixels. Reduced onboarding drop-off 40% at my last role.',
    socialLinks: { portfolio: 'https://example.com', linkedin: 'https://linkedin.com' },
    email: 'sofia.m@example.com',
    phone: '+1-555-002-0001',
    currentBid: 1700,
    category: 'design',
    status: 'active',
    rank: 6,
    peakRank: 6,
    profileViews: 88,
    unlockCount: 4,
    bidCount: 1,
    daysListed: 9,
  },
  {
    name: 'James Osei',
    role: 'Brand Designer',
    roleSlug: 'brand-designer',
    skills: ['Illustrator', 'Figma', 'Brand Identity', 'Motion', 'Typography'],
    summary: 'Visual storyteller. Rebranded 3 companies through Series A. Portfolio speaks for itself.',
    socialLinks: { portfolio: 'https://example.com' },
    email: 'james.osei@example.com',
    phone: null,
    currentBid: 1100,
    category: 'design',
    status: 'active',
    rank: 7,
    peakRank: 7,
    profileViews: 52,
    unlockCount: 2,
    bidCount: 1,
    daysListed: 4,
  },
  // Marketing
  {
    name: 'Rachel Kim',
    role: 'Growth Marketing Manager',
    roleSlug: 'growth-marketing-manager',
    skills: ['SEO', 'Paid Ads', 'Analytics', 'A/B Testing', 'HubSpot'],
    summary: 'Grew organic traffic 3× in 6 months. I run experiments, not gut-feel campaigns.',
    socialLinks: { linkedin: 'https://linkedin.com', x: 'https://x.com' },
    email: 'rachel.k@example.com',
    phone: '+1-555-003-0001',
    currentBid: 1300,
    category: 'marketing',
    status: 'active',
    rank: 8,
    peakRank: 8,
    profileViews: 71,
    unlockCount: 3,
    bidCount: 1,
    daysListed: 6,
  },
  {
    name: 'Carlos Rivera',
    role: 'Content Marketing Lead',
    roleSlug: 'content-marketing-lead',
    skills: ['Content Strategy', 'SEO', 'Copywriting', 'CMS', 'Analytics'],
    summary: 'Built a content engine that drives 80% of inbound leads. Former tech journalist.',
    socialLinks: { linkedin: 'https://linkedin.com' },
    email: 'carlos.r@example.com',
    phone: null,
    currentBid: 800,
    category: 'marketing',
    status: 'active',
    rank: 9,
    peakRank: 9,
    profileViews: 34,
    unlockCount: 1,
    bidCount: 1,
    daysListed: 3,
  },
  // Sales
  {
    name: 'Nadia Thompson',
    role: 'Enterprise Account Executive',
    roleSlug: 'enterprise-account-executive',
    skills: ['Enterprise Sales', 'Salesforce', 'Negotiation', 'SaaS', 'Pipeline Management'],
    summary: '127% of quota last year. Closed a $2.4M ARR deal solo. Looking for Series B+.',
    socialLinks: { linkedin: 'https://linkedin.com' },
    email: 'nadia.t@example.com',
    phone: '+1-555-004-0001',
    currentBid: 1600,
    category: 'sales',
    status: 'active',
    rank: 10,
    peakRank: 10,
    profileViews: 94,
    unlockCount: 6,
    bidCount: 1,
    daysListed: 11,
  },
  {
    name: 'Ben Nakamura',
    role: 'SDR Team Lead',
    roleSlug: 'sdr-team-lead',
    skills: ['Outbound', 'Outreach', 'HubSpot', 'Cold Calling', 'Coaching'],
    summary: 'Ramped from SDR to team lead in 18 months. Built the sequences that booked 40% more demos.',
    socialLinks: { linkedin: 'https://linkedin.com' },
    email: 'ben.n@example.com',
    phone: null,
    currentBid: 700,
    category: 'sales',
    status: 'active',
    rank: 11,
    peakRank: 11,
    profileViews: 28,
    unlockCount: 1,
    bidCount: 1,
    daysListed: 2,
  },
  // Ops
  {
    name: 'Fatima Al-Hassan',
    role: 'Head of Operations',
    roleSlug: 'head-of-operations',
    skills: ['Process Design', 'Notion', 'Hiring', 'Finance', 'Cross-functional Leadership'],
    summary: 'Ops generalist who has scaled orgs from 10 to 100. I make chaos into systems.',
    socialLinks: { linkedin: 'https://linkedin.com' },
    email: 'fatima.ah@example.com',
    phone: '+1-555-005-0001',
    currentBid: 1400,
    category: 'ops',
    status: 'active',
    rank: 12,
    peakRank: 12,
    profileViews: 61,
    unlockCount: 3,
    bidCount: 1,
    daysListed: 7,
  },
  {
    name: 'Tom Brennan',
    role: 'RevOps Manager',
    roleSlug: 'revops-manager',
    skills: ['Salesforce', 'Revenue Operations', 'SQL', 'Forecasting', 'HubSpot'],
    summary: 'Reduced forecast variance by 35% and cut CRM data debt in half. I love unglamorous work.',
    socialLinks: { linkedin: 'https://linkedin.com' },
    email: 'tom.b@example.com',
    phone: null,
    currentBid: 600,
    category: 'ops',
    status: 'active',
    rank: 13,
    peakRank: 13,
    profileViews: 19,
    unlockCount: 0,
    bidCount: 1,
    daysListed: 1,
  },
  {
    name: 'Keiko Tanaka',
    role: 'Machine Learning Engineer',
    roleSlug: 'machine-learning-engineer',
    skills: ['Python', 'PyTorch', 'MLflow', 'AWS SageMaker', 'Data Engineering'],
    summary: 'Shipped an LLM fine-tuning pipeline that cut inference cost by 60%. Looking for applied ML roles.',
    socialLinks: { github: 'https://github.com', linkedin: 'https://linkedin.com' },
    email: 'keiko.t@example.com',
    phone: '+1-555-001-0014',
    currentBid: 500,
    category: 'engineering',
    status: 'active',
    rank: 14,
    peakRank: 14,
    profileViews: 44,
    unlockCount: 2,
    bidCount: 1,
    daysListed: 1,
  },
  {
    name: 'Alex Rivera',
    role: 'UX Researcher',
    roleSlug: 'ux-researcher',
    skills: ['User Interviews', 'Usability Testing', 'Figma', 'Dovetail', 'Survey Design'],
    summary: 'Insights-driven researcher with 5 years in fintech. Turned 3 cancelled features into winners.',
    socialLinks: { portfolio: 'https://example.com', linkedin: 'https://linkedin.com' },
    email: 'alex.r@example.com',
    phone: null,
    currentBid: 300,
    category: 'design',
    status: 'active',
    rank: 15,
    peakRank: 15,
    profileViews: 12,
    unlockCount: 0,
    bidCount: 1,
    daysListed: 1,
  },
];

async function main() {
  console.log('Seeding database...');

  // Clear existing seed data — handle FK constraints
  const seedCandidates = await prisma.candidate.findMany({
    where: { email: { endsWith: '@example.com' } },
    select: { id: true },
  });
  const seedIds = seedCandidates.map((c) => c.id);
  if (seedIds.length > 0) {
    await prisma.profileView.deleteMany({ where: { candidateId: { in: seedIds } } });
    await prisma.unlock.deleteMany({ where: { candidateId: { in: seedIds } } });
    await prisma.bid.deleteMany({ where: { candidateId: { in: seedIds } } });
    await prisma.candidate.deleteMany({ where: { id: { in: seedIds } } });
  }

  for (let i = 0; i < candidates.length; i++) {
    const data = candidates[i];
    const { status, rank, peakRank, profileViews, unlockCount, bidCount, daysListed, ...rest } =
      data;

    const candidate = await prisma.candidate.create({
      data: {
        ...rest,
        status,
        rank,
        peakRank,
        profileViews,
        unlockCount,
        bidCount,
        daysListed,
        createdAt: new Date(Date.now() - daysListed * 86400 * 1000),
      },
    });

    // Create corresponding bid record
    await prisma.bid.create({
      data: {
        candidateId: candidate.id,
        amount: data.currentBid,
        dodoPaymentId: `seed_bid_${i + 1}`,
        createdAt: candidate.createdAt,
      },
    });
  }

  console.log(`Seeded ${candidates.length} candidates.`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());